import { AppActions } from "./AppActions";
import EventsActions from "./EventsActions";
import { ModelActions } from "./ModelActions";
import { ScreenActions } from "./ScreenActions";
import { ShapeActions } from "./ShapeActions";
import UserActions from "./UserActions";

export function getActions(dispatch) {
    return {
        log: (data) => dispatch(EventsActions.log(data)),
        touchDown: () => dispatch(EventsActions.touchDown()),
        touchUp: (touchCount) => dispatch(EventsActions.touchUp(touchCount)),
        touchMove: () => dispatch(EventsActions.touchMove()),
        touchCancel: () => dispatch(EventsActions.touchCancel()),
        activate: () => dispatch(UserActions.activate()),
        abort: () => dispatch(ScreenActions.abort()),
        addDetail: (listKey) => dispatch(ModelActions.addDetail(listKey)),
        addShape: (shape) => dispatch(ScreenActions.addShape(shape)),
        addTable: () => dispatch(ModelActions.addTable()),
        arrangePanels: ({ hor, vert }) => dispatch(ScreenActions.arrangePanels({ hor, vert })),
        cancel: () => dispatch(ScreenActions.cancel()),
        cancelMoving: () => dispatch(ScreenActions.cancelMoving()),
        createPanel: (options) => dispatch(ShapeActions.createPanel(options)),
        deleteConfirm: () => dispatch(ScreenActions.deleteConfirm()),
        deleteRow: (listKey, id) => dispatch(ModelActions.deleteRow(listKey, id)),
        deleteRowConfirm: (listKey, param) => dispatch(ModelActions.deleteRowConfirm(listKey, param)),
        deleteSelectedPanels: () => dispatch(ScreenActions.deleteSelectedPanels()),
        deleteActiveTable: () => dispatch(ModelActions.deleteActiveTable()),
        deleteTableConfirm: () => dispatch(ModelActions.deleteTableConfirm()),
        flipOrientation: () => dispatch(ScreenActions.flipOrientation()),
        goToActiveTable: () => dispatch(ScreenActions.goToActiveTable()),
        loadDetailList: (listKey) => dispatch(ModelActions.loadDetailList(listKey)),
        logout: () => dispatch(UserActions.logout()),
        movePanel: (panel, movePoint) => dispatch(ShapeActions.movePanel(panel, movePoint)),
        open: () => dispatch(ModelActions.openProject()),
        new: () => dispatch(ModelActions.newProjectConfirm()),
        print: ({ save }) => dispatch(ScreenActions.print({ save })),
        requestLanguage: (lang) => dispatch(AppActions.requestLanguage(lang)),
        save: () => dispatch(ModelActions.saveProject()),
        setActiveTable: (tableIndex) => dispatch(ModelActions.setActiveTable(tableIndex)),
        setComplectCount: (count) => dispatch(ModelActions.setComplectCount(count)),
        setCursor: (cursor) => dispatch(ScreenActions.setCursor(cursor)),
        setDeleteConfirm: (value) => dispatch(ModelActions.setDeleteConfirm(value)),
        setDetailProperty: (index, key, value, listKey) => dispatch(ModelActions.setDetailProperty(index, key, value, listKey)),
        setDrawModule: (draw) => dispatch(ModelActions.setDrawModule(draw)),
        setInformation: (info) => dispatch(ModelActions.setInformation(info)),
        setLanguage: (captions) => dispatch(AppActions.setLanguage(captions)),
        setMaterial: (mat) => dispatch(ModelActions.setMaterial(mat)),
        setPrevStatus: () => dispatch(ScreenActions.setPrevStatus()),
        setRealWidth: (width) => dispatch(ScreenActions.setRealWidth(width)),
        setScale: (scale, anchor) => dispatch(ScreenActions.setScale(scale, anchor)),
        setScreenStatus: (status, params) => dispatch(ScreenActions.setScreenStatus(status, params)),
        setToken: (token, remember) => dispatch(UserActions.setToken(token, remember)),
        showAlert: (show, message) => dispatch(AppActions.showAlert(show, message)),
        showConfirm: (show, messageKey, actions) => dispatch(AppActions.showConfirm(show, messageKey, actions)),
        showHelp: (show) => dispatch(AppActions.showHelp(show)),
        startMeasuring: () => dispatch(ScreenActions.startMeasuring()),
        startSelection: (point) => dispatch(ScreenActions.startSelection(point)),
        stopSelection: (isSelectedPanels) => dispatch(ScreenActions.stopSelection(isSelectedPanels)),
        updatePlacedDetails: () => dispatch(ScreenActions.updatePlacedDetails()),
        updateState: () => dispatch(ModelActions.updateState()),
    }
}